//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feedhub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class add
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Discription { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public int advertiser_id { get; set; }
        public int Category_id { get; set; }
        public int Shop_id { get; set; }
        public string Image { get; set; }
        public int Address_id { get; set; }
    
        public virtual Address Address { get; set; }
    }
}
