//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feedhub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReviewInfo()
        {
            this.Shops = new HashSet<Shop>();
        }
    
        public int ID { get; set; }
        public int AccountInfo { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public int Price { get; set; }
        public string Offer { get; set; }
        public int Commnentinfo { get; set; }
        public string DescriptionInfo { get; set; }
    
        public virtual AccountInfo AccountInfo1 { get; set; }
        public virtual Comment Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shops { get; set; }
    }
}
