//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feedhub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int ID { get; set; }
        public int AccountInfo { get; set; }
        public int ReviewInfo { get; set; }
        public string Type { get; set; }
        public string Discription { get; set; }
    
        public virtual AccountInfo AccountInfo1 { get; set; }
        public virtual ReviewInfo ReviewInfo1 { get; set; }
    }
}
