//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oder
    {
        public int Oder_id { get; set; }
        public System.DateTime Oder_date { get; set; }
        public int Amount { get; set; }
        public int Product_id { get; set; }
    
        public virtual product product { get; set; }
    }
}
